### ISSUE TITLE
Issue with help

### ISSUE THREAD

**Issue by danqa** [ndaversa/hubot-jira-bot#13]
Hi there.

I have installed the hubot jira bot and it works properly in slack in terms of functionality. However, the help is not available. If I type "jira help" I get no response from Hubot. If I type "help jira" i get "No available commands match jira." Not sure why the commands are not available when the commands themselves work.

**Comment by ndaversa** [comment]
@danqa if you direct message hubot `jira help` should work.

if you are in a channel you need to do `hubot jira help`

Where `hubot` is the name of your hubot

**Comment by danqa** [comment]
@ndaversa 

This is not working for either direct messages or from a room (See below):

```[Mon May 23 2016 16:28:56 GMT+0000 (UTC)] DEBUG Executing listener callback for Message 'hubot jira help'
2016-05-23T16:28:56.783770+00:00 app[web.1]: [Mon May 23 2016 16:28:56 GMT+0000 (UTC)] ERROR TypeError: Cannot call method 'map' of undefined
2016-05-23T16:28:56.783779+00:00 app[web.1]:   at Function.Help.forTopic (/app/node_modules/hubot-jira-bot/src/help.coffee:16:18, <js>:18:632)
2016-05-23T16:28:56.783780+00:00 app[web.1]:   at TextListener.callback (/app/node_modules/hubot-jira-bot/src/index.coffee:312:7, <js>:430:37)
2016-05-23T16:28:56.783782+00:00 app[web.1]:   at executeListener (/app/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
2016-05-23T16:28:56.783783+00:00 app[web.1]:   at allDone (/app/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
2016-05-23T16:28:56.783783+00:00 app[web.1]:   at /app/node_modules/hubot/node_modules/async/lib/async.js:274:13
2016-05-23T16:28:56.783784+00:00 app[web.1]:   at Object.async.eachSeries (/app/node_modules/hubot/node_modules/async/lib/async.js:142:20)
2016-05-23T16:28:56.783785+00:00 app[web.1]:   at Object.async.reduce (/app/node_modules/hubot/node_modules/async/lib/async.js:268:15)
2016-05-23T16:28:56.783785+00:00 app[web.1]:   at /app/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
2016-05-23T16:28:56.783786+00:00 app[web.1]:   at process._tickCallback (node.js:458:13)
2016-05-23T16:28:56.783788+00:00 app[web.1]:
2016-05-23T16:28:56.783838+00:00 app[web.1]: [Mon May 23 2016 16:28:56 GMT+0000 (UTC)] ERROR DOES NOT COMPUTE
2016-05-23T16:28:56.783939+00:00 app[web.1]: [Mon May 23 2016 16:28:56 GMT+0000 (UTC)] DEBUG Sending reply
2016-05-23T16:28:56.784068+00:00 app[web.1]: [Mon May 23 2016 16:28:56 GMT+0000 (UTC)] DEBUG Sending to testing: <@U0J5UT63S>: DOES NOT COMPUTE

**Comment by ndaversa** [comment]
@danqa My guess is you are missing some environment variables, if you look at help.coffee it uses a few `Config` variables...

https://github.com/ndaversa/hubot-jira-bot/blob/master/src/help.coffee

you can see all the env vars needed in: https://github.com/ndaversa/hubot-jira-bot/blob/master/src/config.coffee check for `process.env`

Once you set those up, let me know if you still have issues.

**Comment by danqa** [comment]
@ndaversa That fix it. Thanks.
