### ISSUE TITLE
Syntax error on install

### ISSUE THREAD

**Issue by aaronware** [ndaversa/hubot-jira-bot#4]
```[Fri Nov 27 2015 18:41:09 GMT+0000 (UTC)] ERROR Unable to load /app/node_modules/hubot-jira-bot/src/jira: SyntaxError: Unexpected token u
2015-11-27T18:41:09.832141+00:00 app[web.1]:   at Object.parse (native)
2015-11-27T18:41:09.832143+00:00 app[web.1]:   at module.exports (/app/node_modules/hubot-jira-bot/src/jira.coffee:36:29, <js>:23:18)```

**Comment by Legoless** [comment]
Getting same here.

**Comment by ijunes** [comment]
Make sure your environment variables don't have quotes around them.
Correct:
   HUBOT_JIRA_PROJECTS_MAP=\{\"web\":\"web\",\"android\":\"AND\",\"ios\":\"IOS\"\}
Incorrect:
  HUBOT_JIRA_PROJECTS_MAP="\{\"web\":\"SFT\",\"android\":\"AND\",\"ios\":\"IOS\"\}"

**Comment by murali2020kris** [comment]
HUBOT_JIRA_PROJECTS_MAP={"web":"web","android":"AND","ios":"IOS"}
] ERROR Unable to load /home/mkrish6/tars/node_modules/hubot-jira-bot/src/index: SyntaxError: Unexpected token w in JSON at position 1
  at Object.parse (native)
  at /home/mkrish6/tars/node_modules/hubot-jira-bot/src/config.coffee:36:5, <js>:30:22
  at Object.<anonymous> (/home/mkrish6/tars/node_modules/hubot-jira-bot/src/config.coffee:21:1, <js>:197:5)
  at Object.<anonymous> (/home/mkrish6/tars/node_modules/hubot-jira-bot/src/config.coffee:21:1, <js>:201:4)
  at Module._compile (module.js:570:32)
  at Object.loadFile (/home/mkrish6/tars/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (/home/mkrish6/tars/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/home/mkrish6/tars/node_modules/hubot-jira-bot/src/index.coffee:23:10, <js>:8:12)
  at Object.<anonymous> (/home/mkrish6/tars/node_modules/hubot-jira-bot/src/index.coffee:20:1, <js>:563:4)
  at Module._compile (module.js:570:32)
  at Object.loadFile (/home/mkrish6/tars/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (/home/mkrish6/tars/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Robot.loadFile (/home/mkrish6/tars/node_modules/hubot/src/robot.coffee:355:9, <js>:224:20)
  at /home/mkrish6/tars/node_modules/hubot-jira-bot/index.coffee:7:5, <js>:13:22
  at FSReqWrap.cb [as oncomplete] (fs.js:257:19)

**Comment by alexanto09** [comment]
Hi
Place the JSON values inside single quotes for the configurations.
Please find the config that I am using :
export HUBOT_JIRA_PRIORITIES_MAP='[{"name":"Blocker","id":"1"},{"name":"Critical","id":"2"},{"name":"Major","id":"3"},{"name":"Minor","id":"4"},{"name":"Trivial","id":"5"}]'
export HUBOT_JIRA_PROJECTS_MAP='{"web":"WEB","android":"AN","ios":"IOS","platform":"PLAT"}'
export HUBOT_JIRA_TRANSITIONS_MAP='[{"name":"triage","jira":"Triage"},{"name":"icebox","jira":"Icebox"},{"name":"backlog","jira":"Backlog"},{"name":"devready","jira":"Selected for Development"},{"name":"inprogress","jira":"In Progress"},{"name":"design","jira":"Design Triage"}]'
export HUBOT_JIRA_TYPES_MAP='{"story":"Story","bug":"Bug","task":"Task"}'
export HUBOT_JIRA_FIELDS='["issuetype","status","assignee","reporter","summary","description","labels","project"]'
export HUBOT_SLACK_BUTTONS='{"watch":{"name":"watch","text":"Watch","type":"button","value":"watch","style":"primary"},"assign":{"name":"assign","text":"Assign to me","type":"button","value":"assign"},"devready":{"name":"devready","text":"Dev Ready","type":"button","value":"selected"},"inprogress":{"name":"inprogress","text":"In Progress","type":"button","value":"progress"},"rank":{"name":"rank","text":"Rank Top","type":"button","value":"top"},"running":{"name":"running","text":"Running","type":"button","value":"running"},"review":{"name":"review","text":"Review","type":"button","value":"review"},"resolved":{"name":"resolved","text":"Resolved","type":"button","style":"primary","value":"resolved"},"done":{"name":"done","text":"Done","type":"button","style":"primary","value":"done"}}'
export HUBOT_SLACK_PROJECT_BUTTON_STATE_MAP='{"PLAT":{"inprogress":["review","running","resolved"],"review":["running","resolved"],"running":["resolved"],"resolved":["devready","inprogress"],"mention":["watch","assign","devready","inprogress","rank"]},"HAL":{"inprogress":["review","running","resolved"],"review":["running","resolved"],"running":["resolved"],"resolved":["devready","inprogress"],"mention":["watch","assign","devready","inprogress","rank"]},"default":{"inprogress":["review","done"],"review":["done"],"done":["devready, inprogress"],"mention":["watch","assign","devready","inprogress","rank"]}}'
