### ISSUE TITLE
invalid json response Unexpected token <

### ISSUE THREAD

**Issue by Gyadav** [ndaversa/hubot-jira-bot#49]
Hi,

I have successfully integrated the same, however on each command I get below error, can you please suggest what might be going wrong in this case, Thanks a lot...!!!

[Mon Jan 15 2018 18:24:22 GMT+0530 (IST)] ERROR FetchError: invalid json response body at https://XXX.XXX.XXX/jira/rest/api/2/search reason: Unexpected token <
    at /home/gyadav/myhubot/node_modules/hubot-jira-bot/node_modules/node-fetch/lib/body.js:48:31
    at process._tickCallback (node.js:369:9)

**Comment by nikhilgorantla** [comment]
@Gyadav Can you help me on how to set up the log output of Jirabot -- Hubot
